### ISSUE TITLE
Checklist preparativos para el evento

### ISSUE THREAD

**Issue by eafelix** [banodejs/Bienvenido#4]
Aqui va definida la lista para no perder ningún punto en la organización de los eventos. 
Puntos que surgen de nuestra propia experiencia, recomendaciones de otras comunidades, etc.
Obviamente todos somos libres de ir discutiendo y corrigiendo cosas.

- [ ]  Confirmar hosts
- [ ]  Confirmar sponsors 
- [ ]  Confirmar Charlas ( 2 charlas de 20 a 30 minutos cada uno con espacio a lighting talk)
- [ ]  Confirmar Fecha y Hora (Preferentemente)
- [ ]  Actualizar Web con los datos de sponsors , fechas 
- [ ]  Actualizar Meetup y abrir la inscripción 
- [ ]  Generar Formulario de confirmación 
- [ ]  Ver extras como stickers , snacks , etc.  

Para ver Checklist de items necesarios en host entrar en este issue: 

Para ver Checklist de items necesarios para difusion entrar en este issue:

**Comment by a0viedo** [comment]
Esto no debería ir en el repo organizadores?

**Comment by eafelix** [comment]
si si manquee ahora lo cierro y lo paso
